# Generated by Django 4.2.2 on 2023-06-21 18:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Defectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_defectos', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre_defectos'],
            },
        ),
        migrations.CreateModel(
            name='Empaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empaque', models.CharField(max_length=100, verbose_name='Tipo De Empaque')),
                ('tara', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Tara')),
            ],
            options={
                'ordering': ['tipo_empaque'],
            },
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fruta', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre_fruta'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_historico', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_entrada', to='operaciones.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_salida', to='operaciones.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.CharField(max_length=100, verbose_name='Numero De Item')),
                ('kilos_netos', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_negociacion', models.CharField(choices=[('Con Devolucion', 'Con Devolucion'), ('Venta Nacional', 'Venta Nacional'), ('Sin Devolucion', 'Sin Devolucion')], max_length=50, verbose_name='Tipo De Negociacion')),
                ('porcen_muestreo', models.IntegerField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tipo_muestreo', models.CharField(blank=True, choices=[('Ingreso De Fruta', 'Ingreso De Fruta'), ('Seguimiento En Linea', 'Seguimiento En Linea')], max_length=50, null=True, verbose_name='Tipo De Muestreo')),
                ('lider_muestreo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lider De Muestreo')),
                ('emp_muestreo', models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Cantidad Empaque Muestreo')),
                ('emp_nacional', models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Cantidad Empaque Nacional')),
                ('desecho', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Desecho')),
                ('numero_remsion', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Numero De Remision')),
                ('conductor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conductor o Proveedor')),
                ('cedula_pro', models.IntegerField(blank=True, max_length=12, null=True, verbose_name='Cedula Provedoor o Conductor')),
                ('bodega', models.ForeignKey(default='Recibo', on_delete=django.db.models.deletion.CASCADE, to='operaciones.bodega')),
                ('defectos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.defectos')),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.fruta')),
                ('patinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.empleados')),
                ('tip_empaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.empaque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
    ]
