# Generated by Django 4.2.2 on 2023-06-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='t_negociacion',
            field=models.CharField(max_length=50, verbose_name='Tipo Negociacion'),
        ),
    ]
