# Generated by Django 4.2.2 on 2023-06-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_remove_item_defectos_item_defectos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='desecho',
        ),
    ]
