# Generated by Django 4.2.2 on 2023-07-13 23:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0002_alter_movimiento_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientosmuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_historico_muestreo', models.CharField(max_length=100)),
                ('porcentaje_muestreo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje Muestreado')),
                ('tipo_muestreo', models.CharField(max_length=50, verbose_name='Tipo Muestreo')),
                ('lider_muestreo', models.CharField(max_length=50, verbose_name='Lider De Muestreo')),
                ('empaque_muestreo', models.CharField(max_length=50, verbose_name='Cantidad Empaque Muestreo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Muestreo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
