# Generated by Django 4.2.2 on 2023-06-22 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_remove_item_desecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
