# Generated by Django 4.2.2 on 2023-06-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_alter_item_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Ingreso Recibo'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Movimiento'),
        ),
    ]
