# Generated by Django 4.2.2 on 2023-06-22 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_item_fecha_alter_movimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Ingreso Recibo'),
        ),
    ]
