from django.urls import path
from . import views
from .views import JornadaListView


urlpatterns = [
    path("", views.nomina_home, name="nomina_home"),
    path('registrohoras', views.registrohoras, name='registrohoras'), 
    path('home_nomina', views.home_nomina, name='home_nomina'),
    path('jornadas/', views.jornadas, name='jornadas'),
    path('jornadas/lista/', views.list_jornadas, name='lista_jornadas'),
    path('jornadas/crear/', views.crear_jornada, name='crear_jornada'),
    path('jornadas/actualizar/<int:jornada_id>/', views.actualizar_jornada, name='actualizar_jornada'),
    path('jornadas/eliminar/<int:jornada_id>/', views.eliminar_jornada, name='eliminar_jornada'),
    path('jornadas/importar/', views.importar_excel_jor, name='import_jornada'),
    path('jornadas/exportar/', views.export_jor_excel, name='export_jornada'),
    path('empleados/', views.empleados, name='empleados'),
    path('empleados/lista/', views.list_empleados, name='lista_empleados'),
    path('empleados/crear/', views.crear_empleado, name='crear_empleado'),
    path('empleados/actualizar/<int:empleado_id>/', views.actualizar_empleado, name='actualizar_empleado'),
    path('festivos/crear/', views.crear_festivo, name='crear_festivo'),
    path('festivos/exportar/', views.export_festivos_excel, name='export_festivos'),
    path('festivos/importar/', views.importar_excel_festivos, name='importar_festivos'),
    path('empleados/importar/', views.importar_excel_emp, name='import_empleado'),
    path('empleados/exportar/', views.export_emp_excel, name='export_empleado'),
    path('cargos/importar/', views.importar_excel_cargo, name='import_cargo'),
    path('cargos/exportar/', views.export_cargos_excel, name='export_cargo'),
    path('cargos/crear/', views.crear_cargo, name='crear_cargo'),
    path('operaciones/', views.ope_home, name='ope_home'),
    path('operaciones/jornadas/', views.ope_jornadas, name='ope_jornadas'),
    path('operaciones/jornadas/lista/', views.ope_list_jornadas, name='ope_lista_jornadas'),
    path('operaciones/jornadas/crear/', views.ope_crear_jornada, name='ope_crear_jornada'),
    path('operaciones/jornadas/actualizar/<int:jornada_id>/', views.ope_actualizar_jornada, name='ope_actualizar_jornada'),
    path('operaciones/jornadas/eliminar/<int:jornada_id>/', views.ope_eliminar_jornada, name='ope_eliminar_jornada'),
    path('operaciones/jornadas/importar/', views.ope_importar_excel_jor, name='ope_import_jornada'),
    path('operaciones/jornadas/exportar/', views.ope_export_jor_excel, name='ope_export_jornada'),
    path('operaciones/empleados/', views.ope_empleados, name='ope_empleados'),
    path('operaciones/empleados/lista/', views.ope_list_empleados, name='ope_lista_empleados'),
    path('operaciones/festivos/ver/', views.ope_crear_festivo, name='ope_crear_festivo'),
    path('operaciones/cargos/ver/', views.ope_crear_cargo, name='ope_crear_cargo'),
    path('prueba', JornadaListView.as_view(), name='prueba'),
]
